//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleRandomClient.DoubleRandom {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoubleRandom.IDoubleRandom")]
    public interface IDoubleRandom {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoubleRandom/GetDoubleDom", ReplyAction="http://tempuri.org/IDoubleRandom/GetDoubleDomResponse")]
        double GetDoubleDom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoubleRandom/GetDoubleDom", ReplyAction="http://tempuri.org/IDoubleRandom/GetDoubleDomResponse")]
        System.Threading.Tasks.Task<double> GetDoubleDomAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoubleRandomChannel : DoubleRandomClient.DoubleRandom.IDoubleRandom, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoubleRandomClient : System.ServiceModel.ClientBase<DoubleRandomClient.DoubleRandom.IDoubleRandom>, DoubleRandomClient.DoubleRandom.IDoubleRandom {
        
        public DoubleRandomClient() {
        }
        
        public DoubleRandomClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoubleRandomClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoubleRandomClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoubleRandomClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetDoubleDom() {
            return base.Channel.GetDoubleDom();
        }
        
        public System.Threading.Tasks.Task<double> GetDoubleDomAsync() {
            return base.Channel.GetDoubleDomAsync();
        }
    }
}
