//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormDoubleRandom.DoubleRandom {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoubleRandom.IDoubleRandom")]
    public interface IDoubleRandom {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoubleRandom/GetDoubleDom", ReplyAction="http://tempuri.org/IDoubleRandom/GetDoubleDomResponse")]
        double GetDoubleDom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoubleRandom/GetDoubleDom", ReplyAction="http://tempuri.org/IDoubleRandom/GetDoubleDomResponse")]
        System.Threading.Tasks.Task<double> GetDoubleDomAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoubleRandom/GetDoubleList", ReplyAction="http://tempuri.org/IDoubleRandom/GetDoubleListResponse")]
        double[] GetDoubleList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoubleRandom/GetDoubleList", ReplyAction="http://tempuri.org/IDoubleRandom/GetDoubleListResponse")]
        System.Threading.Tasks.Task<double[]> GetDoubleListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoubleRandom/SetDoubleList", ReplyAction="http://tempuri.org/IDoubleRandom/SetDoubleListResponse")]
        void SetDoubleList(double Tolist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoubleRandom/SetDoubleList", ReplyAction="http://tempuri.org/IDoubleRandom/SetDoubleListResponse")]
        System.Threading.Tasks.Task SetDoubleListAsync(double Tolist);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoubleRandomChannel : FormDoubleRandom.DoubleRandom.IDoubleRandom, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoubleRandomClient : System.ServiceModel.ClientBase<FormDoubleRandom.DoubleRandom.IDoubleRandom>, FormDoubleRandom.DoubleRandom.IDoubleRandom {
        
        public DoubleRandomClient() {
        }
        
        public DoubleRandomClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoubleRandomClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoubleRandomClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoubleRandomClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetDoubleDom() {
            return base.Channel.GetDoubleDom();
        }
        
        public System.Threading.Tasks.Task<double> GetDoubleDomAsync() {
            return base.Channel.GetDoubleDomAsync();
        }
        
        public double[] GetDoubleList() {
            return base.Channel.GetDoubleList();
        }
        
        public System.Threading.Tasks.Task<double[]> GetDoubleListAsync() {
            return base.Channel.GetDoubleListAsync();
        }
        
        public void SetDoubleList(double Tolist) {
            base.Channel.SetDoubleList(Tolist);
        }
        
        public System.Threading.Tasks.Task SetDoubleListAsync(double Tolist) {
            return base.Channel.SetDoubleListAsync(Tolist);
        }
    }
}
